CREATE TABLE IF NOT EXISTS account_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    phone VARCHAR(11) NOT NULL,
    nickname VARCHAR(32) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'STUDENT',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_account_user_phone UNIQUE (phone),
    CONSTRAINT ck_account_user_role CHECK (role IN ('STUDENT', 'ORGANIZER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
